remote_theme: alshedivat/al-folio@master
plugins:
- jekyll-remote-theme

title: Ball Recognizer
description: An image classification API that classifies 20 different types of sports balls used around the world

author:
  name: Naosher Mustakim